# Project: Project5-2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.c5-2.o sum.c5-2.o sub.c5-1.o
LINKOBJ  = main.c5-2.o sum.c5-2.o sub.c5-1.o
LIBS     = -L"C:/Users/82107/Dev-Cpp/MinGW64/lib" -L"C:/Users/82107/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/82107/Dev-Cpp/MinGW64/include" -I"C:/Users/82107/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/82107/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/82107/Dev-Cpp/MinGW64/include" -I"C:/Users/82107/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/82107/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/82107/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project5-2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.c5-2.o: main.c5-2.c
	$(CC) -c main.c5-2.c -o main.c5-2.o $(CFLAGS)

sum.c5-2.o: sum.c5-2.c
	$(CC) -c sum.c5-2.c -o sum.c5-2.o $(CFLAGS)

sub.c5-1.o: sub.c5-1.c
	$(CC) -c sub.c5-1.c -o sub.c5-1.o $(CFLAGS)
